### ISSUE TITLE
Add Roadmap summary to Fsharp.org website

### ISSUE THREAD

**Issue by jackfoxy** [fsharp/fssf-ask-the-board#10]
# [Question/Proposal]: Title

Add Roadmap summary to Fsharp.org website

# Description
[description]: #description

There should be a summary of the current Microsoft and community roadmap for the F# language and tools. Phillip typically composes such a document every 6 months or so, but it is easy to forget where it is

# Motivation and impact
[motivation]: #motivation

Community members frequently want to know the direction Microsoft is steering it's F# team towards and what their concerns are.

This will give more visibility into F# language and tool development.

# Proposed solution and alternatives
[solution]: #solution

The F#.org website should have a prominent link to the latest Microsoft F# roadmap. 

Alternatively, the website should have a roadmap page that Phillip updates every 6 months.

**Comment by voronoipotato** [comment]
Firstly apologies for the extremely long time without a response. I'll be working to make sure there's always a timely response to board questions starting now. 

I think that may be a good idea, if you do a pull request at https://github.com/fsharp/fsfoundation or at least an issue we can merge it in. Additionally if you want to also add it to our rework at https://github.com/fsharp/fssf-website that would be nice. Thanks for the suggestion
