### ISSUE TITLE
Ranked voting of OSS issues and language suggestions

### ISSUE THREAD

**Issue by jackfoxy** [fsharp/fssf-ask-the-board#11]
This is a template for creating issues in **fssf-ask-the-board** repository.

You are welcome to use sections below as a guidance. 

In the case if some of the sections are not applicable to your question or proposal, feel free to skip them. In the case if some of sections are missing, please feel free to add them to your issue.

We appreciate and welcome as much information in your issue as possible, it will help the Board address it.

# [Question/Proposal]: Ranked voting of OSS issues and language suggestions

# Description
[description]: #description

F# Foundation members can rank and submit their top 5 OSS issues (from any F# OSS project) and language issues every 30 days.

The F#.org website displays ranking of submissions.

# Motivation and impact
[motivation]: #motivation

This provides a means of ranking and prioritizing what is important to the community.

This would provide actionable information for questions like "what projects should interns and mentor/mentees work on".

# Proposed solution and alternatives
[solution]: #solution

Allow F# foundation members to submit a list of up to 5 OSS/fslang-design issue URIs. Members can submit a new list every 30 days. Rank-ordered results published on the website.

I don't know the best way to implement this. 

# Drawbacks
[drawbacks]: #drawbacks

This may dependent on the website re-write, as I don't know the best way to submit votes for tabulation.

In order to prevent repeat voting, voting would not be entirely anonymous to the maintainers of the system. 

# Are you willing to help?

Yes.

**Comment by voronoipotato** [comment]
This is a fun idea and goes with some of the goals the community has around more OSS involvement. Since this is a website improvement I'd recommend posting it as an issue on https://github.com/fsharp/fsfoundation . Thanks again!
