### ISSUE TITLE
Assume responsibility for official FSharp documentation from MSDN

### ISSUE THREAD

**Issue by jmhickman** [fsharp/fssf-ask-the-board#12]
# [Proposal]: Assume responsibility for official FSharp documentation from MSDN

# Description
[description]: #description

The MSDN documentation for the language contains numerous 404/dead links, which makes learning about certain modules or concepts high friction. The documentation's state gives the *impression*, true or false, that there exists a certain disregard for the language from its largest sponsor. I feel this is one source of the frequent 'is FSharp dead/does it have a future' questions.

I learned from a [recent thread](https://forums.fsharp.org/t/where-are-the-standard-library-docs/1401) that the community maintains some documentation elsewhere. Since the push is for the community to 'own' the language, I think a great step in that direction would be for the primary documentation to move to fsharp.org.

# Motivation and impact  
[motivation]: #motivation  

*Why is this proposal or question important?*
I've been working with FSharp for about 3-4 months now, and have produced one reasonably-sized project [here](https://github.com/jmhickman/Fetters). I've been consistently concerned about broken and underwhelming documentation while consulting the MSDN site for FSharp. My opinion is that this experience makes the language *feel* second class. Perhaps there were others who felt that way as well but didn't stick with the language as a result.

*Who will benefit from it and in which way?*

Keeping tidy and up-to-date documentation gives the strong impression that the maintainers _care_. It also shows dedication to fundamentals that, at least to me, would seem obvious to professional developers. 

Speaking for myself, I couldn't care less about interpolated strings. I *do* care that **every single link in this snippet is broken**

![image](https://user-images.githubusercontent.com/6581761/90318875-1ba14c00-def9-11ea-88a4-6fff0e961626.png)

*Why we can't afford not to do it?*

I think the intent of the question is something like "Why is this important enough to sink resources into?"

The answer is that first-class languages have first class documentation. Be first class.

# Proposed solution and alternatives
[solution]: #solution

*How much work/effort do you think it will take?*

To transform FSharp's documentation into something first class would be a great deal of effort indeed, because it would have to come from the people who understand it best. Has someone asked Scott Wlaschin how many man-hours he's spent on [his site](https://www.fsharpforfunandprofit.com)? Because providing the reference **and** the demonstration of core language forms and primitives would be even more than that. 

*In case you already have some ideas on how to address the issue, list them here.*

Optimally, the board would leverage its ties with Microsoft to consume and then extend the base of documentation already extant on MSDN. That would provide a meaningful addition to the documentation scattered all over the place. But from there it's all an uphill slog.

*Are there any alternatives to this idea already?*

There are existing sources of knowledge elsewhere, but the whole point is to pull in the best representation of that knowledge to the official home of the language. Therefore there is no meaningful alternative. In fact, we're living the alternative right now.

# Drawbacks
[drawbacks]: #drawbacks

*Why should we **not** do this? Any risks or doubts?*

It's time intensive and tedious. 

It's not exciting like new features.

It's not critical like language bugs.

Writing documentation well is teaching, and not just anyone is a good teacher, thus narrowing the pool of qualified individuals to accomplish the task further.

To make it the best requires the direct input of the principals, who are probably really busy.

# Are you willing to help?

I don't know enough to help. Literally. I don't know enough to be able to contribute first party documentation. The best I could do is provide feedback on style, comprehensibility, etc. 

*Would you be interested in helping with implementing the idea, or resolution of the question described?*

Of course. I'm doing that right now. 

*Who could be interested to help?*

I don't know. If the logical people haven't done it already, I'm surely not qualified to nominate anyone else.

# Other thoughts
[other]: #other-thoughts

*Anything else relevant to the question or idea.*

I really like this language. I dislike object programming, and FSharp is the only language that actually lets me write code that intrinsically makes sense to me, and that runs on .Net. But it is a **FIGHT** sometimes to learn how to do a thing, or how to do a thing idiomatically, or which of the 3 ways I could do a thing is the correct one, etc. And the frustration I experience when I look in the dotnet API pages and see every code example is in C# is real. It means that practically speaking, I need to learn a language and a half to write well in just one. 

And that's just nonsense.

**Comment by ScottHutchinson** [comment]
I think this is very important to the growth of the F# community. @dsyme has started some documentation improvements recently, so it would be interesting to get his perspective on this issue. @cartermp @baronfel

**Comment by baronfel** [comment]
The community does maintain a parallel set of API docs (source code [here](https://github.com/fsharp/fsharp-core-docs)), and discussions are ongoing at that repo what level of integration between docs.microsoft.com and those docs should be.

These community docs are expressly linked on fsharp.org (check the Learn Menu -> API Docs), and the F# conceptual documentation at docs.microsoft.com are really great and are the very first link on the Learn page.

**Comment by cartermp** [comment]
The reference is in place, just some more links have to change. I submitted a dozen or so PRs to do that, welcome to have more folks collaborate

**Comment by jmhickman** [comment]
So it indeed seems like there's some discussion in the linked repo, so I'll have a look around there and see where I would be able to make a difference. I'm sort of surprised that the discussions are as young as they are.

The [repo](https://github.com/dotnet/docs) that I assume @cartermp is talking about seems a little...busy. I don't have much confidence that stuff is going to be fixed in a timely manner there, if my experience with really busy Issue Trackers is a guide. But clearly it's what is supposed to happen, so as I come across broken things I'll make new issues for them. Would it be best to make new issues for each link? Or just collect all the links in one issue?

**Comment by cartermp** [comment]
Actually if you look at F# specific issues there's a pretty good ration of open/closed, with most of the reported issues not being actual problems but requests for a little more clarification or new content: https://github.com/dotnet/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22%3Abooks%3A+Area+-+F%23+Guide%22

Specifically for the links, every issue reported has a PR that addresses it, the majority of which have already been merged, and will go live in 24 hours as the repo does a pass to push things to the live site. Part of the reason it might seem "busy" is because I submitted ~45 pull requests over the weekend to address various reports, not just those related to links.

**Comment by jmhickman** [comment]
I see, that makes sense then. Well, going forward I will submit issues as I run into things.

Since there's already discussion around the docs in another location and the specific issue of busted links I singled out is already in queue to be addressed, I suppose this issue can be closed then as it doesn't bring anything new. I don't know what the etiquette is on this repo about closing issues so I won't immediately do it myself.

**Comment by cartermp** [comment]
I think it would be very helpful to go here: https://fsharp.github.io/fsharp-core-docs/ and file issues about problems you have or things you think need improving here: https://github.com/fsharp/fsharp-core-docs

The issue of broken links should be resolved pretty quickly, but there's a lot of work to be done to make the FSharp.Core reference great 🙂

**Comment by ScottHutchinson** [comment]
Currently, when I get a 404, the error page offers alternative links, which are not relevant to F# documentation. I hope something is being done to fix that issue. For example: https://docs.microsoft.com/en-us/dotnet/fsharp/microsoft.fsharp.core-namespace-%5Bfsharp%5D

**Comment by cartermp** [comment]
As mentioned, links are already being fixed so there are no 404s.
