### ISSUE TITLE
The fsharp.org website should show some code

### ISSUE THREAD

**Issue by julienXX** [fsharp/fssf-ask-the-board#2]
F# is beautiful IMO and the website should show some basic code on the main page in order for users to get a glimpse of it. See rust-lang.org or haskell.org for example.

**Comment by lenadroid** [comment]
Thanks for submitting this issue to the board's attention! 

Feel free to share it with other people in F# community for more comments on this. Also, if you find any specific examples that are fitting in your opinion - please, add it to the issue!

**Comment by sergey-tihon** [comment]
Renovate http://www.tryfsharp.org (migrate to Fable) and merge/link with fsharp.org ?

**Comment by Neftedollar** [comment]
We have some code examples at [Russian speakers F# community site](http://fsharplang.ru) but this code not good as I think. It would be nice to get a code from the official community site for general vision.

**Comment by Krzysztof-Cieslak** [comment]
> Renovate http://www.tryfsharp.org (migrate to Fable) and merge/link with fsharp.org ?

I believe it's super good idea! ;]

**Comment by FoggyFinder** [comment]
>We have some code examples at [Russian speakers F# community site](https://github.com/fsharp/fssf-ask-the-board/issues/fsharplang.ru) but this code not good as I think

It seems like you mean this [site](http://fsharplang.ru)

**Comment by Neftedollar** [comment]
@FoggyFinder yes, thank you! I've updated my comment.

**Comment by FSSF** [comment]
This is being moved to be part of the overall website discussion: fsharp/fsfoundation#682

For details, please see fsharp/fsfoundation#680
