### ISSUE TITLE
Have a single http://fsharp.org/use that detects platform

### ISSUE THREAD

**Issue by dsyme** [fsharp/fssf-ask-the-board#3]
The "install F#" experience is clunky, and there is no single URL to point people to like http://fsharp.org/use.  (I point people to http://fsharp.org instead). This URL should detect platform and make a default one-click install link available for the #1 option for linux/mac/windows/..., plus other options

**Comment by lenadroid** [comment]
Thanks for bringing this up, Don!

**Comment by mathias-brandewinder** [comment]
[personal opinion, not the board's opinion]
+100 to that suggestion. Detecting platform would be nice, but at the very least having one page/url to direct people to would be very handy. In the current state of affairs, there is no good landing point/url, which requires giving newcomers instructions like "go to fsharp.org, look for the use menu, then follow the instructions".

**Comment by baronfel** [comment]
A simple solution would be to host a page at `/use` that uses something like https://github.com/antivanov/sniffr to determine OS and redirect to the appropriate page.

**Comment by FSSF** [comment]
This is being moved to be part of the overall website discussion: https://github.com/fsharp/fsfoundation/issues/681

For details, please see https://github.com/fsharp/fsfoundation/issues/680
