### ISSUE TITLE
FSharp Example Projects (F# ExPro)

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/fssf-ask-the-board#6]
# F-Sharp by example

# Description

I am a newbie, studying the theoretical aspects of programming since about 6 months.
F# seems like a huuge improvement compared other languages in terms of readability and conciseness.
My issue is, that the very most tutorials on programming are essentially language documentation.

It's like somebody explains to you how to hold a hammer, nails and other tools and says then:

"Now, build a house."

I see empathy as a possible solution.

Once you can feel and think in the position of the other one, is it far easier to explain things.
Pair programming studies show that developers who are much more skilled as their partner are not as helpful as role models as devs who are about on the same level.

I already see this issue appearing up in my own case:
Things who were unbelievable challenging to me a few months ago are quite fine today.
And it seems like I loose the ability to explain some primitive things.

I think this is since our brain focuses always on a specific job.

So it's sane to develop tutorials from the point of view from somebody who is actually aware of the current situation for the beginner?

I see recipes in cookbooks as a nice approach, since they show how to solve specific tasks.
Whats even saner, in my opinion, is a book that takes you by the hand and goes with you through a whole project. Like: How to build a small video game.

I am really motivated to do something for our community, both F# and the open source scene in general.

And in order to do so, can I currently offer all kinds of non-programming stuff, so including writing tutorials and creating screencasts of things I am already aware of.

One of the most helpful guides I experienced is this short series: [The dev aspect](https://www.youtube.com/channel/UCAiiOTio8Yu69c3XnR7nQBQ)

F# offers us newbies currently the sanest option in my opinion since we get a ML-like language which compiles on .NET Core.

To me, it is quite challenging "to start somewhere", since I am theoretically aware about the tools, while I still lack understanding of the different environments, like databases and stuff.

I am quite aware that there is documentation about them as well, while this suggestion here is about the creation of some tutorials, who have practical value and show the potential of F-Sharp in the real world.

I see F# as a potential newbie language since its expressive, concise and rich.

# Motivation and impact

See above. :)

*Who will benefit from it and in which way?*

The whole universe. 

# Proposed solution and alternatives

See above.

# Drawbacks

Oh, this is the sweetest spot. Imho, there is less to say against comprehensive documentation. 

# Are you willing to help?

Sure.

**Comment by baronfel** [comment]
Hi @ShalokShalom, thanks for your question! And many, many apologies for the delay in answering this question.

There are a number of good middle-level tutorials that already exist for various stacks in the F# space, especially if you are looking for web technologies:

- [Suave Music Store](https://www.gitbook.com/book/theimowski/suave-music-store/details) - This one covers web, postgresql database, build, and deployment via docker
- [SAFE Stack Bookstore](https://github.com/SAFE-Stack/SAFE-BookStore) - This one covers web backend, web frontend, Azure Table Storage databases, build, and deployment via docker to Azure or Google Cloud
- [SAFE Nightwatch](https://github.com/SAFE-Stack/SAFE-Nightwatch) - This one covers using Fable and React Native to do mobile app development.
- [SAFE Conference Planner](https://github.com/SAFE-Stack/SAFE-ConfPlanner) - This one covers using CQRS/Event-Sourcing as a functional database, Websockets, and client/server side F#. In addition it covers Web site styling using Fulma.
- [F# RealWorld Example App](https://github.com/gothinkster/fsharp-realworld-example-app) - This is an F# implementation of the [RealWorld](https://github.com/gothinkster/realworld) spec. It's made with Suave and Mongodb.

These are just a few of the examples I've found over the past few months. They are pretty web-heavy, but that's where a lot of innovation in the F# community is these days.

If you think there are technologies where there's room for larger examples, I'd suggest dropping by the Slack and seeing if there are others willing to help out to make something of similar quality to the examples above!

**Comment by ShalokShalom** [comment]
Thanks a lot for your help. As said, I am looking for beginner level tutorials. Suave is, so far as I am informed, a low level library.

Do you really think, this is something useful for complete programming newbies?
